Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 60
TracerRateTicks: 5
PilotTool: 345 #Compass
WorldGuardBlockMoveOnBuildPerm: false
WorldGuardBlockSinkOnPVPPerm: false
ManOverBoardTimeout: 15
FireballLifespan: 6
FireballPenetration: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: true
FadeWrecksAfter: 0
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
BlockQueueChunkSize: 1000
AllowCrewSigns: true
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
TownyBlockMoveOnSwitchPerm: false
TownyBlockSinkOnNoPVP: false
TownyWorldHeightLimits:
  world:
    worldMin: -1
    worldMax: -1
    aboveTownSpawn: 96
    underTownSpawn: 255
